blank_issues_enabled: false
contact_links:
  - name: Doom550D Discussions
    url: https://github.com/lauris-nl/doom550d/discussions
    about: Ask questions and discuss ideas with the Doom550D community.
